### PR TITLE
easier LUFA install

### PR DESCRIPTION
**Pull request by CrazyRedMachine**
Hi, i've just helped someone on C&S flashing your code cause he had trouble with the instructions from Palatis repo (no administrator access to his terminal...). 

I think as your repo is growing in popularity it's best to refer to the easier install method for LUFA to avoid dealing with such issues (the aforementioned person did manage to flash your code succesfully quickly after reading these updated instructions)

### CODE REVIEW

**Comment by oocyberkevinoo** [comment]
If I remember correctly, all my tests building like this were not great.
This method is still needed for other Pro Micro boards...
So I guess I can add it as an easy install for compatible boards, but don't know what boards except Leonardo.

Let me know, I'll check that for sure.

**Comment by CrazyRedMachine** [comment]
all avr compatible boards are added as custom lufa boards using this method, if your pro micro is a 3.3v then you have to pick lilypad rather than leonardo, if it's a 5v pro micro then you can pick leonardo.

if you're having trouble with this method the right thing to do would have been to tell me this way I can possibly update my repo... 

all this being said, looks like Palatis finally gave maintainer rights to another guy so this lufa install method from the board manager will soon become the main way too.

**Comment by oocyberkevinoo** [comment]
In that case, I'll do some tests later I guess, and depending of the results, I'll do so.
Thank you for letting me know about that.

**Comment by CrazyRedMachine** [comment]
this method has been working for a lot of people, including someone who was trying to flash your code on his pro micro.... so yea if it doesn't work for you let me know and i'll guide you through the steps.

**Comment by oocyberkevinoo** [comment]
We tried this right now, and have issue re-flashing a board by resetting...

**Comment by CrazyRedMachine** [comment]
flashing by reset works the same as it did before, only difference between my pr and base code is the way the lufa boards are installed on your system (this basically makes a copy so you can just select the correct board type, instead of having to temporarily mod your arduino board files)

lufa code doesn't include the arduino cdc endpoint, so there's no magic reset feature, you need to actually press the reset button once the code is compiled and the ide is looking for the board to flash (i suggest enabling verbose output during compilation and upload in the preferences menu, makes it easier to know when to reset)

**Comment by oocyberkevinoo** [comment]
Actually, the problem is that the person compiled for LUFA Lilipad as it was recognized as Lilypad board, but we should compile as Sparkfun Pro Micro, or Arduino Leonardo instead

But now, reset button works, but Arduino IDE can't fin or upload it
We don't know why

**Comment by CrazyRedMachine** [comment]
if it was 3.3v pro micro then lilypad is ok from what i've seen before.

what does the verbose say during upload?

**Comment by oocyberkevinoo** [comment]
Well, actually, he just badly wired the RST button, so it's working now.
We still have a pin acting REALLY weird in Lilipad build, so we tried something else, but maybe it's not related... What do you think about that ? (he have some buttons triggering randomly)

**Comment by CrazyRedMachine** [comment]
honestly my first guess would be if rst button was badly wired, i'd check the other one as well... i'm not sure if lilypad has any difference compared to pro micro (also worth mentioning i think arduino-lufa has only been thoroughly tested on leonardo (or 5v pro micro which is the same thing).. all the other boards are there "because avr based")

**Comment by oocyberkevinoo** [comment]
I think he had issues on soldering, I really don't think there is any way for that to happen... The slider is working perfectly, but Btn0 and 3 seems to just randomly want to trigger itself.

Still, your setup is now tested by myself and working perfectly, sorry it took that much time :/

**Comment by CrazyRedMachine** [comment]
triggering by itself looks more like faulty switch than bad soldering, but yea I doubt it can be due to the firmware or board selection... 

glad to know the easier install is working fine for you :D you'll see it makes it way simpler to handle having both lufa and non-lufa arduino projects ^^

**Pull request merged**
